/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ModestInterface -p modest_interface_p.h:modest_interface.cpp modest-email-dbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MODEST_INTERFACE_P_H_1274948439
#define MODEST_INTERFACE_P_H_1274948439

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.nokia.modest
 */
class ModestInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.nokia.modest"; }

public:
    ModestInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ModestInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> ComposeMail(const QString &to, const QString &cc, const QString &bcc, const QString &subject, const QString &body, const QString &attachments)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(to) << qVariantFromValue(cc) << qVariantFromValue(bcc) << qVariantFromValue(subject) << qVariantFromValue(body) << qVariantFromValue(attachments);
        return asyncCallWithArgumentList(QLatin1String("ComposeMail"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace nokia {
    typedef ::ModestInterface modest;
  }
}
#endif
