Document: qvernote
Title: Debian qvernote Manual
Author: <insert document author here>
Abstract: This manual describes what qvernote is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qvernote/qvernote.sgml.gz

Format: postscript
Files: /usr/share/doc/qvernote/qvernote.ps.gz

Format: text
Files: /usr/share/doc/qvernote/qvernote.text.gz

Format: HTML
Index: /usr/share/doc/qvernote/html/index.html
Files: /usr/share/doc/qvernote/html/*.html

  
